# Generated by Django 4.2.7 on 2024-01-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_alter_courses_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='discription',
            new_name='description',
        ),
    ]
